theme: jekyll-theme-dinky

# Jekyll Ayarlar覺
markdown: kramdown # Markdown motoru
kramdown:
  input: GFM # GitHub Flavored Markdown
  syntax_highlighter: rouge # Kod renklendirici
permalink: pretty # URL yap覺s覺 (pretty: /yazi-ad覺/)
